// Navigation constants
export const TOOGLE_NAVIGATION_DRAWER = "TOOGLE_NAVIGATION_DRAWER";
export const CHANGE_NAVBAR_HEADING = "CHANGE_NAVBAR_HEADING";

// Editor constants
export const UPDATE_EDITOR_TITLE = "UPDATE_EDITOR_TITLE";
export const UPDATE_EDITOR_BODY = "UPDATE_EDITOR_BODY";
export const UPDATE_EDITOR_SLUG = "UPDATE_EDITOR_SLUG";
export const UPDATE_EDITOR_CATEGORY = "UPDATE_EDITOR_CATEGORY";
export const ADD_EDITOR_TAG = "ADD_EDITOR_TAG";
export const REMOVE_EDITOR_TAG = "REMOVE_EDITOR_TAG";
export const UPDATE_EDITOR_FEATURED_IMAGE = "UPDATE_EDITOR_FEATURED_IMAGE";
export const SAVE_AS_DRAFT = "SAVE_AS_DRAFT";

// Category constants
export const UPDATE_ALL_CATEGORIES = "UPDATE_ALL_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
