// Navigation constants
export const TOOGLE_NAVIGATION_DRAWER = "TOOGLE_NAVIGATION_DRAWER";
export const CHANGE_NAVBAR_HEADING = "CHANGE_NAVBAR_HEADING";

// Editor constants
export const UPDATE_EDITOR_TITLE = "UPDATE_EDITOR_TITLE";
export const UPDATE_EDITOR_BODY = "UPDATE_EDITOR_BODY";
export const UPDATE_EDITOR_SLUG = "UPDATE_EDITOR_SLUG";
export const UPDATE_EDITOR_CATEGORY = "UPDATE_EDITOR_CATEGORY";
export const ADD_EDITOR_TAG = "ADD_EDITOR_TAG";
export const REMOVE_EDITOR_TAG = "REMOVE_EDITOR_TAG";
export const UPDATE_EDITOR_FEATURED_IMAGE = "UPDATE_EDITOR_FEATURED_IMAGE";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const CLEAR_EDITOR = "CLEAR_EDITOR";
export const LOAD_POST_TO_EDITOR = "LOAD_POST_TO_EDITOR";

// Category constants
export const UPDATE_ALL_CATEGORIES = "UPDATE_ALL_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

// Posts constants
export const UPDATE_ALL_POSTS = "UPDATE_ALL_POSTS";
